# Dev domain
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ftm-ingress
spec:
  rules:
  - host: longops.io.vn
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ftm-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ftm-frontend-service
            port:
              number: 80
