apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftm-production

resources:
  - namespace.yaml
  - ../../base

patchesStrategicMerge:
  - replicas-patch.yaml

# Jenkins sáº½ update image tags
images:
  - name: acrftmbackenddev.azurecr.io/ftm-backend
    newTag: latest
  - name: acrftmfrontenddev.azurecr.io/ftm-frontend
    newTag: latest

commonLabels:
  environment: production
